---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: expense-db-mysql
spec:
  provider: vault
  secretObjects:
    - secretName: expense-db-mysql
      type: Opaque
      data:
        - objectName: expense-db-username
          key: username
        - objectName: expense-db-password
          key: password
  parameters:
    roleName: 'expense'
    vaultAddress: 'http://vault.vault:8200'
    objects: |
      - objectName: "expense-db-username"
        secretPath: "expense/database/mysql/creds/expense"
        secretKey: "username"
      - objectName: "expense-db-password"
        secretPath: "expense/database/mysql/creds/expense"
        secretKey: "password"