---
apiVersion: v1
kind: Service
metadata:
  name: expense-db-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: expense-db-mysql
    framework: mysql
spec:
  selector:
    app: expense-db-mysql
    framework: mysql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-db-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: expense-db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-db-mysql
  template:
    metadata:
      labels:
        app: expense-db-mysql
        framework: mysql
    spec:
      serviceAccountName: expense-db-mysql
      containers:
        - name: expense-db-mysql
          image: "joatmon08/expense-db:mysql-8"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expense-db-mysql
                  key: password
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 60