kind: Secret
apiVersion: v1
metadata:
  name: expense-db-mysql
  annotations:
    avp.kubernetes.io/path: "expense/static/mysql"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  password: <password>