apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-db
  namespace: openshift-gitops
spec:
  destination:
    namespace: expenses
    server: https://kubernetes.default.svc
  project: expense-report
  source:
    path: database
    repoURL: https://github.com/joatmon08/vault-argocd.git
    targetRevision: main
    plugin:
      env:
        - name: VAULT_ADDR
          value: 'http://vault.vault.svc:8200'
        - name: AVP_K8S_ROLE
          value: argocd
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: k8s
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
