apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense
  namespace: openshift-gitops
spec:
  destination:
    namespace: expenses
    server: https://kubernetes.default.svc
  project: expense-report
  source:
    path: expense
    repoURL: https://github.com/joatmon08/vault-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
