---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: static
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: vault-admin
  type: kv
  path: expense
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: postgresql-password-policy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: vault-admin
  passwordPolicy: |
    length = 12
    rule "charset" {
      charset = "abcdefghijklmnopqrstuvwxyz"
    }
    rule "charset" {
      charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      min-chars = 1
    }
    rule "charset" {
      charset = "0123456789"
      min-chars = 1
    }
    rule "charset" {
      charset = "!@"
      min-chars = 1
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: vault-admin
  path: expense/static
  secretKey: password
  secretFormat:
    passwordPolicyName: postgresql-password-policy
  refreshPeriod: 5m